# Generated by Django 5.0.4 on 2024-05-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventar',
            old_name='my_image',
            new_name='image',
        ),
    ]
