# Generated by Django 5.0.4 on 2024-06-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
