# Generated by Django 5.0.4 on 2024-06-13 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='disc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='imag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imageernkol', to='main.images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='main',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
