# Generated by Django 5.0.4 on 2024-05-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventar',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
