# Generated by Django 5.0.4 on 2024-05-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_inventar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventar',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
